# Налаштування збірки
[build]
  # Папка, де знаходяться ваші бекенд-функції
  functions = "functions"
  
  # Папка для публікації. Оскільки index.html знаходиться в корені, ми вказуємо "."
  publish = "."

# Правила перенаправлення для API
[[redirects]]
  # Усі запити, що починаються з /api/
  from = "/api/*"
  
  # будуть перенаправлені на відповідну функцію Netlify
  to = "/.netlify/functions/:splat"
  
  # Статус 200 означає, що це не редирект, а проксі-запит
  status = 200